# Data Preprocessing

In [69]:
import pandas as pd 

df=pd.read_csv('Bank-Customers.csv')
df.index=df.index+1
df

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
1,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
2,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
3,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
4,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
5,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79
...,...,...,...,...,...,...,...,...,...
4010,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4011,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4012,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4013,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4014,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

## checking column names

In [70]:
df.columns

Index(['Customer ID', 'Name', 'Surname', 'Gender', 'Age', 'Region',
       'Job Classification', 'Date Joined', 'Balance'],
      dtype='object')

In [71]:
df.isnull().sum()

Customer ID           0
Name                  0
Surname               0
Gender                0
Age                   0
Region                0
Job Classification    0
Date Joined           0
Balance               0
dtype: int64

In [72]:
import pandas as pd 
df1=pd.read_csv("customers.csv")
df.index=df.index+1
df

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
2,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
3,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
4,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
5,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
6,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79
...,...,...,...,...,...,...,...,...,...
4011,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4012,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4013,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4014,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4015,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

In [73]:
df.isnull().sum()

Customer ID           0
Name                  0
Surname               0
Gender                0
Age                   0
Region                0
Job Classification    0
Date Joined           0
Balance               0
dtype: int64

In [74]:
import pandas as pd 

df3=pd.read_csv("Salaries.csv")
df3.index=df3.index+1
df

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
2,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
3,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
4,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
5,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
6,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79
...,...,...,...,...,...,...,...,...,...
4011,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4012,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4013,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4014,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4015,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

## checking null values in the data set

In [75]:
df3.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

## checking null values in the data set in percentile

In [76]:
df3.isnull().sum()/len(df3)*100

Id                    0.000000
EmployeeName          0.000000
JobTitle              0.000000
BasePay               0.409676
OvertimePay           0.002691
OtherPay              0.002691
Benefits             24.326961
TotalPay              0.000000
TotalPayBenefits      0.000000
Year                  0.000000
Notes               100.000000
Agency                0.000000
Status              100.000000
dtype: float64

In [77]:
df3.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

## if we  have more than 30% of null values , we have to drop that particualr column

In [78]:
df3.drop(columns=['Notes','Status'],inplace=True)

In [79]:
df3.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Agency'],
      dtype='object')

In [80]:
df3['Benefits']
df3['Benefits']=df3['Benefits'].bfill()

In [81]:
df3['Benefits'].isnull().sum()

np.int64(0)

In [82]:
df3['BasePay']=df3['BasePay'].fillna(df3['BasePay'].mean)

In [83]:
df3['OvertimePay']=df3['OvertimePay'].fillna(df3['OvertimePay'].median)

In [84]:
df3['OtherPay']=df3['OtherPay'].fillna(df3['OtherPay'].mode)

In [86]:
df3.isnull().sum()

Id                  0
EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
Agency              0
dtype: int64

### finally we handle the null values in this data set

## data pre-proceesing is completed⭐⭐⭐